#
# .swiftlint.yml
#
excluded:
- Pods
- Podfile
- Podfile.lock
- R.generated.swift
- fastlane
- slather
- vendor
- Gemfile
- Gemfile.lock
- Carthage
- Qass-DevelopTests
- Qass-DevelopUITests

disabled_rules:
- variable_name
- type_name
- nesting
- cyclomatic_complexity
- type_body_length
- function_body_length
- multiple_closures_with_trailing_closure
- file_length

# error to warning
force_try: warning
force_cast: warning

cyclomatic_complexity:
- 10 # warning

line_length:
- 300 # warning

type_body_length:
- 400 # warning

file_length:
- 500 # warning

function_body_length:
- 100 # warning
