#
# .swiftlint.yml
#
excluded:
- Pods
- Podfile
- Podfile.lock
- R.generated.swift

disabled_rules:
- trailing_whitespace
- line_length
- nesting
- variable_name
- force_cast
- force_try
- cyclomatic_complexity
- type_name
- function_body_length
