#
# .swiftlint.yml
#
excluded:
- Pods
- Podfile
- Podfile.lock
- R.generated.swift
- fastlane
- slather
- vendor
- Gemfile
- Gemfile.lock
- Carthage

disabled_rules:
- line_length
- nesting
- variable_name
- force_cast
- force_try
- cyclomatic_complexity
- type_name
- function_body_length
- file_length
- type_body_length
- trailing_comma
