#
# .swiftlint.yml
#
excluded:
- Pods
- Podfile
- Podfile.lock
- R.generated.swift
- fastlane
- slather
- vendor
- Gemfile
- Gemfile.lock
- Carthage

disabled_rules:
- variable_name
- force_cast
- force_try
- cyclomatic_complexity
- type_name

line_length:
- 180

type_body_length:
- 400

file_length:
- 500

function_body_length:
- 100
