#
# .swiftlint.yml
#
excluded:
- Pods
- Podfile
- Podfile.lock
- R.generated.swift
- fastlane
- slather
- vendor
- Gemfile
- Gemfile.lock
- Carthage
- Amby-DevelopTests
- Amby-DevelopUITests

disabled_rules:
- nesting
- variable_name
- type_name
- cyclomatic_complexity
- type_body_length
- function_body_length
- multiple_closures_with_trailing_closure
- notification_center_detachment

# error to warning
force_try: warning
force_cast: warning

cyclomatic_complexity:
- 10 # warning

line_length:
- 300 # warning

type_body_length:
- 400 # warning

file_length:
- 600 # warning

function_body_length:
- 100 # warning
