references:
  defaults: &defaults
    macos:
      xcode: "11.1.0"
    working_directory: ~/project
    shell: /bin/bash --login -eo pipefail
    environment:
      TZ: "/usr/share/zoneinfo/Asia/Tokyo"
      LANG: "en_US.UTF-8"
      LC_ALL: "en_US.UTF-8"
  setup_bundler: &setup_bundler
    # Bundler Setup
    - run:
        name: Which bundler?
        command: bundle -v
    # Bundler Cache
    - restore_cache:
        keys:
          - gem-cache-v1-{{ checksum "Gemfile.lock" }}
    - run: bundle install --path vendor/bundle
    - save_cache:
        key: gem-cache-v1-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle
    setup_carthage: &setup_carthage
      - restore_cache:
          key: carthage-cache-v1-{{ checksum "Cartfile.resolved" }}
      - run:
          name: bootstrap
          command: ./bootstrap.sh
      - save_cache:
          key: carthage-cache-v1-{{ checksum "Cartfile.resolved" }}
          paths:
            - Carthage

version: 2
jobs:
  build-and-test:
    <<: *defaults
    steps:
      - checkout:
          path: ~/project
      - *setup_bundler
      - *setup_carthage
      - run:
          name: Build
          command: bundle exec fastlane ios dev

  danger:
    <<: *defaults
    steps:
      - checkout:
          path: ~/project
      - *setup_bundler
      - run: bundle exec danger

workflows:
  version: 2
  build-test-lint:
    jobs:
      - danger
      - build-and-test:
          requires:
            - danger
          filters:
            branches:
              only:
                - develop
