version: 2.1

executors:
  defaults:
    macos:
      xcode: "11.1.0"
    working_directory: ~/project
    shell: /bin/bash --login -eo pipefail
    environment:
      TZ: "/usr/share/zoneinfo/Asia/Tokyo"
      LANG: "en_US.UTF-8"
      LC_ALL: "en_US.UTF-8"

commands:
  checkout_src:
    steps:
      - checkout:
          path: ~/project

  setup_ruby:
    steps:
      - run:
          name: Set Ruby Version
          command: |
            # echo "ruby-2.4" > ~/.ruby-version
            ruby -v

  setup_gems:
    steps:
      - restore_cache:
          keys:
            - gem-cache-v2-{{ checksum "Gemfile.lock" }}
            - gem-cache-v2-
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: gem-cache-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

  setup_carthage:
    steps:
      - restore_cache:
          keys:
            - carthage-cache-v2-{{ checksum "Cartfile.resolved" }}
            - carthage-cache-v2-
      - run:
          name: bootstrap
          command: ./bootstrap.sh
      - save_cache:
          key: carthage-cache-v2-{{ checksum "Cartfile.resolved" }}
          paths:
            - Carthage

jobs:
  build-and-test:
    executor:
      name: defaults
    steps:
      - checkout_src
      - setup_ruby
      - setup_gems
      - setup_carthage
      - run:
          name: Build
          command: bundle exec fastlane ios dev

  danger:
    executor:
      name: defaults
    steps:
      - checkout_src
      - setup_ruby
      - setup_gems
      - run:
          name: Danger
          command: bundle exec danger

workflows:
  version: 2
  build-test-lint:
    jobs:
      - danger
      - build-and-test:
          requires:
            - danger
          filters:
            branches:
              only:
                - develop
