references:
  defaults: &defaults
    macos:
      xcode: "11.1.0"
    working_directory: ~/project
    shell: /bin/bash --login -eo pipefail
    environment:
      BUNDLER_VERSION: 1.17.2
      TZ: "/usr/share/zoneinfo/Asia/Tokyo"
      LANG: "en_US.UTF-8"
      LC_ALL: "en_US.UTF-8"

version: 2
jobs:
  danger:
    <<: *defaults
    docker:
      - image: dantoml/danger:latest
        environment:
         - TZ: "/usr/share/zoneinfo/Asia/Tokyo"
         - LANG: ja_JP.UTF-8
         - LC_ALL: C.UTF-8
         - LANGUAGE: ja_JP.UTF-8
    steps:
      - checkout
      - run: gem install danger-todoist
      - run: danger

  build-and-test:
    <<: *defaults
    steps:
      - checkout:
          path: ~/project
      # Carthage Setup
      - restore_cache:
          key: dev-ca-{{ checksum "Cartfile.resolved" }}
      - run:
          name: bootstrap
          command: ./bootstrap.sh
      - save_cache:
          key: dev-ca-{{ checksum "Cartfile.resolved" }}
          paths:
            - Carthage
      # Bundler Setup
      - run:
          name: Which bundler?
          command: bundle -v
      # Bundler Install & Cache
      - restore_cache:
          keys:
            - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gem-cache-v1-{{ arch }}-{{ .Branch }}
            - gem-cache-v1
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      # Build
      - run:
          name: Build
          command: bundle exec fastlane ios dev

workflows:
  version: 2
  check_and_build:
    jobs:
      - danger
      - build-and-test:
          requires:
            - danger
          filters:
            branches:
              only:
                - develop