references:
  defaults: &defaults
    macos:
      xcode: "11.1.0"
    working_directory: ~/project
    shell: /bin/bash --login -eo pipefail
    environment:
      TZ: "/usr/share/zoneinfo/Asia/Tokyo"
      LANG: "en_US.UTF-8"
      LC_ALL: "en_US.UTF-8"

version: 2
jobs:
  build:
    <<: *defaults
    branches:
      only:
        - develop
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          key: dev-ca-{{ checksum "Cartfile.resolved" }}
      - run:
          name: bootstrap
          command: ./bootstrap.sh
      - save_cache:
          key: dev-ca-{{ checksum "Cartfile.resolved" }}
          paths:
            - Carthage
      - run:
          name: Update bundler
          command: yes | sudo gem install bundler
      - run:
          name: install gems
          command: bundle install --path vendor/bundle
      - run:
          name: Build
          command: bundle exec fastlane ios dev
