references:
  defaults: &defaults
    macos:
      xcode: "11.1.0"
    working_directory: ~/project
    shell: /bin/bash --login -eo pipefail
    environment:
      TZ: "/usr/share/zoneinfo/Asia/Tokyo"
      LANG: "en_US.UTF-8"
      LC_ALL: "en_US.UTF-8"
  checkout_src: &checkout_src
    checkout:
      path: ~/project
  setup_ruby: &setup_ruby
    run:
      name: Set Ruby Version
      command: |
        echo "ruby-2.4" > ~/.ruby-version
        ruby -v
  setup_gems: &setup_gems
    restore_cache:
      keys:
        - gem-cache-v2-{{ checksum "Gemfile.lock" }}
        - gem-cache-v2-
    run: bundle install --path vendor/bundle
    save_cache:
      key: gem-cache-v2-{{ checksum "Gemfile.lock" }}
      paths:
        - vendor/bundle
  setup_carthage: &setup_carthage
    restore_cache:
      keys:
        - carthage-cache-v2-{{ checksum "Cartfile.resolved" }}
        - carthage-cache-v2-
    run:
      name: bootstrap
      command: ./bootstrap.sh
    save_cache:
      key: carthage-cache-v2-{{ checksum "Cartfile.resolved" }}
      paths:
        - Carthage

version: 2
jobs:
  build-and-test:
    <<: *defaults
    steps:
      - *checkout_src
      - *setup_ruby
      - *setup_gems
      - *setup_carthage
      # Build
      - run:
          name: Build
          command: bundle exec fastlane ios dev

  danger:
    <<: *defaults
    steps:
      - *checkout_src
      - *setup_ruby
      - *setup_gems
      - run:
          name: Danger
          command: bundle exec danger

workflows:
  version: 2
  build-test-lint:
    jobs:
      - danger
      - build-and-test:
          requires:
            - danger
          filters:
            branches:
              only:
                - develop
