# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#
#
# branch is feature/ci

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
#
# branch is develop

AMBY_APP_ID = ENV['AMBY_APP_ID']
AMBY_PROFILE = ENV['AMBY_PROFILE']
AMBY_TEAM = ENV['AMBY_TEAM']
AMBY_SLACK_URL = ENV['AMBY_SLACK_URL']

default_platform(:ios)

platform :ios do
  before_all do
    ENV["SLACK_URL"] = AMBY_SLACK_URL
    ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "120"
    clear_derived_data(derived_data_path: "../build_dev")

    if is_ci?
        setup_circle_ci
    end
  end

  lane :dev do

    match(
    	type: "adhoc",
      force_for_new_devices: true,
      app_identifier: AMBY_APP_ID,
      readonly: true
    )

    settings_to_override = {
      :BUNDLE_IDENTIFIER => AMBY_APP_ID,
      :PROVISIONING_PROFILE_SPECIFIER => AMBY_PROFILE,
      :DEVELOPMENT_TEAM => AMBY_TEAM
    }

    gym(
      derived_data_path: "../build_dev",
      archive_path: "../build_dev/Amby-dev.xcarchive",
      xcargs: settings_to_override,
      clean: true,
      configuration: "Release",
      export_method: "ad-hoc",
      scheme: "Amby[Local]",
      output_directory: "ipa",
      export_options: {
        compileBitcode: false,
        provisioningProfiles: { 
            AMBY_APP_ID => AMBY_PROFILE
        }
      },
      xcargs: "PROVISIONING_PROFILE_SPECIFIER='#{AMBY_PROFILE}'"
    )
  end

  after_all do |lane|
    commit = last_git_commit
    slack(
      message: "Successfully deployed new app update",
      channel: "#jenkins"
    )
  end

  error do |lane, exception|
    slack(
      message: exception.message,
      channel: "#jenkins",
      success: false
    )
  end

end
