# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :test do
    scan(
      workspace: "Qass.xcworkspace",
      devices: ["iPhone 6s"],
      scheme: "Qass-Develop[UT]",
      code_coverage: true,
      output_types: "html",
      clean: true
    )

    slather(
      cobertura_xml: true,
      output_directory: "./slather/reports",
      proj: "Qass.xcodeproj",
      workspace: "Qass.xcworkspace",
      scheme: "Qass-Develop[UT]"
    )
  end
end
